CREATE TABLE IF NOT EXISTS Customers (
    CustomerID INT  PRIMARY KEY,
    Email VARCHAR(255)  NOT NULL,
    Phone VARCHAR(20), 
    FirstName VARCHAR(255) NOT NULL UNIQUE,
    LastName VARCHAR(20) NOT NULL UNIQUE,
); 